# Generated by Django 4.1.6 on 2023-02-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('chasis', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo'), ('verde', 'VERDE')], max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_matriculacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('tipo_vehiculo', models.CharField(choices=[('coche', 'Coche'), ('ciclomotor', 'Ciclomotor'), ('motocicleta', 'Motocicleta')], max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.marca')),
            ],
        ),
    ]
