# Generated by Django 4.1.6 on 2023-02-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_desbloqueo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_minuto', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, to_field='username', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('coste_final', models.FloatField(null=True)),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.patinete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.usuario')),
            ],
        ),
    ]
